version: "3.8"
services:
  web:
    build:
      context: .
    container_name: web_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - '8000:8000'
    depends_on:
      - db

  db:
    image: postgres:latest

    container_name: db_app

    env_file:
      - .env

    environment:
      POSTGRES_DB: 'bot'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'


  app:
    build:
      context: .
    environment:
      - .env
    container_name: bot
    command: python bot.py run
    env_file:
      - .env
    depends_on:
      - db
