version: "3"
services:
  web:
    build:
      context: .
    container_name: web_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - '8000:8000'
    depends_on:
      - db

  db:
    image: postgres:latest

    container_name: db_app

    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'bot'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'

#
#  app:
#    build:
#      context: .
#    environment:
#      - .env
#    container_name: bot_app
#    command: ["/sport_club_bot_app/docker/bot_app.sh"]
#    depends_on:
#      - db
#      - web
