version: '3'

services:

  db:
    image: postgres:16
    restart: always
    container_name: db_app

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5454:5432'
    networks:
      - my-network

  web:
    build:
      context: .
    container_name: web_app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://your_user:your_password@db:5432/bot_app
    networks:
      - my-network


  app:
    build:
      context: .
    environment:
      - .env
    container_name: bot
    command: python bot.py run
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
