version: "3.9"
services:
  web:
    build:
      context: .
    container_name: web_app
    command: python manage.py makemigrations && python manage.py migrate && python manage.py createsuperuser && python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - '8000:8000'
    depends_on:
      - db
    networks:
      - my-network

  db:
    image: postgres:16
    restart: always
    container_name: db_app

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5454:5432'
    networks:
      - my-network


  app:
    build:
      context: .
    environment:
      - .env
    container_name: bot
    command: python bot.py run
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - my-network
