# Generated by Django 5.0.6 on 2024-06-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('gen_men', 'Men'), ('gen_women', 'Women')], max_length=10)),
                ('phone_number', models.CharField(max_length=12)),
                ('current_standard', models.CharField(max_length=500)),
            ],
        ),
    ]
