# Generated by Django 5.0.6 on 2024-06-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_bot', '0002_standards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('training_history', models.TextField()),
                ('number_of_referral_points', models.IntegerField()),
                ('info_subscription', models.TextField()),
            ],
        ),
    ]
