# Generated by Django 5.0.6 on 2024-06-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_bot', '0005_alter_profile_current_standard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standards',
            name='back_squat',
        ),
        migrations.AlterField(
            model_name='profile',
            name='info_subscription',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='number_of_referral_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='training_history',
            field=models.TextField(default='-'),
        ),
    ]
