# Generated by Django 5.0.6 on 2024-07-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(default='')),
                ('password', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(blank=True, null=True)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('username', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('gender', models.CharField(choices=[('gen_men', 'Мужской'), ('gen_women', 'Женский'), ('gender', 'Неизвестно')], default='gender', max_length=10)),
                ('phone_number', models.CharField(default='', max_length=12)),
                ('training_history', models.TextField(blank=True, default='-', null=True)),
                ('number_of_referral_points', models.IntegerField(blank=True, default=0, null=True)),
                ('info_subscription', models.TextField(blank=True, default='-', null=True)),
                ('current_standard', models.TextField(blank=True, default='-', null=True)),
                ('telegram_status', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Standards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(blank=True, null=True)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('thunder', models.IntegerField(default='0')),
                ('turkish_ascent_axel', models.IntegerField(default='0')),
                ('turkish_ascent_kettlebell', models.IntegerField(default='0')),
                ('bench_press', models.IntegerField(default='0')),
                ('axel_jerk', models.IntegerField(default='0')),
                ('taking_on_axel_chest', models.IntegerField(default='0')),
                ('gluteal_bridge', models.IntegerField(default='0')),
                ('deadlift', models.IntegerField(default='0')),
                ('jerk', models.IntegerField(default='0')),
                ('taking_on_the_chest', models.IntegerField(default='0')),
                ('axel_deadlift', models.IntegerField(default='0')),
                ('classic_squat', models.IntegerField(default='0')),
                ('front_squat', models.IntegerField(default='0')),
                ('squat_over_the_head', models.IntegerField(default='0')),
                ('skipping_rope', models.IntegerField(default='0')),
                ('push_ups', models.IntegerField(default=0)),
                ('shuttle_running', models.IntegerField(default='0')),
                ('farmer_walk', models.IntegerField(default='0')),
                ('pull_ups', models.IntegerField(default='0')),
                ('high_jump', models.IntegerField(default='0')),
                ('long_jump', models.IntegerField(default='0')),
                ('holding_the_axel', models.IntegerField(default='0')),
                ('handstand', models.IntegerField(default='0')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=89898989)),
                ('user_name', models.TextField(default='', max_length=20)),
                ('thunder', models.IntegerField(default='0')),
                ('turkish_ascent_axel', models.IntegerField(default='0')),
                ('turkish_ascent_kettlebell', models.IntegerField(default='0')),
                ('bench_press', models.IntegerField(default='0')),
                ('axel_jerk', models.IntegerField(default='0')),
                ('taking_on_axel_chest', models.IntegerField(default='0')),
                ('gluteal_bridge', models.IntegerField(default='0')),
                ('deadlift', models.IntegerField(default='0')),
                ('jerk', models.IntegerField(default='0')),
                ('taking_on_the_chest', models.IntegerField(default='0')),
                ('axel_deadlift', models.IntegerField(default='0')),
                ('classic_squat', models.IntegerField(default='0')),
                ('front_squat', models.IntegerField(default='0')),
                ('squat_over_the_head', models.IntegerField(default='0')),
                ('skipping_rope', models.IntegerField(default='0')),
                ('push_ups', models.IntegerField(default=0)),
                ('shuttle_running', models.IntegerField(default='0')),
                ('farmer_walk', models.IntegerField(default='0')),
                ('pull_ups', models.IntegerField(default='0')),
                ('high_jump', models.IntegerField(default='0')),
                ('long_jump', models.IntegerField(default='0')),
                ('holding_the_axel', models.IntegerField(default='0')),
                ('handstand', models.IntegerField(default='0')),
                ('month', models.TextField(choices=[('1', 'Январь'), ('4', 'Апрель'), ('7', 'Июль'), ('10', 'Октябрь')], default='7')),
                ('year', models.TextField(default=2024)),
            ],
        ),
        migrations.CreateModel(
            name='StatisticsGet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.TextField(default='')),
                ('year', models.TextField(default=2024)),
            ],
        ),
    ]
