# Generated by Django 5.0.6 on 2024-06-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='user_name',
            field=models.TextField(default='your name', max_length=20),
        ),
    ]
