# Generated by Django 5.0.6 on 2024-06-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('training_history', models.TextField(default='-')),
                ('number_of_referral_points', models.IntegerField(default=0)),
                ('info_subscription', models.TextField(default='-')),
                ('current_standard', models.TextField(default='-')),
            ],
        ),
        migrations.CreateModel(
            name='Standards',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('thunder', models.IntegerField(default=0)),
                ('turkish_ascent_axel', models.IntegerField(default=0)),
                ('turkish_ascent_kettlebell', models.IntegerField(default=0)),
                ('bench_press', models.IntegerField(default=0)),
                ('axel_jerk', models.IntegerField(default=0)),
                ('taking_on_axel_chest', models.IntegerField(default=0)),
                ('gluteal_bridge', models.IntegerField(default=0)),
                ('deadlift', models.IntegerField(default=0)),
                ('jerk', models.IntegerField(default=0)),
                ('taking_on_the_chest', models.IntegerField(default=0)),
                ('axel_deadlift', models.IntegerField(default=0)),
                ('classic_squat', models.IntegerField(default=0)),
                ('front_squat', models.IntegerField(default=0)),
                ('squat_over_the_head', models.IntegerField(default=0)),
                ('skipping_rope', models.IntegerField(default=0)),
                ('push_ups', models.IntegerField(default=0)),
                ('shuttle_running', models.IntegerField(default=0)),
                ('farmer_walk', models.IntegerField(default=0)),
                ('pull_ups', models.IntegerField(default=0)),
                ('high_jump', models.IntegerField(default=0)),
                ('long_jump', models.IntegerField(default=0)),
                ('holding_the_axel', models.IntegerField(default=0)),
                ('handstand', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('gen_men', 'Men'), ('gen_women', 'Women')], max_length=10)),
                ('phone_number', models.CharField(max_length=12)),
            ],
        ),
    ]
